#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-pluggy
Version  : 0.9.0
Release  : 49
URL      : https://files.pythonhosted.org/packages/a7/8c/55c629849c64e665258d8976322dfdad171fa2f57117590662d8a67618a4/pluggy-0.9.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/a7/8c/55c629849c64e665258d8976322dfdad171fa2f57117590662d8a67618a4/pluggy-0.9.0.tar.gz
Summary  : plugin and hook calling mechanisms for python
Group    : Development/Tools
License  : MIT
Requires: deprecated-pluggy-license = %{version}-%{release}
Requires: deprecated-pluggy-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : deprecated-setuptools_scm-legacypython
BuildRequires : python-core
BuildRequires : setuptools-legacypython
BuildRequires : setuptools_scm

%description
====================================================
pluggy - A minimalist production ready plugin system
====================================================

%package legacypython
Summary: legacypython components for the deprecated-pluggy package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-pluggy package.


%package license
Summary: license components for the deprecated-pluggy package.
Group: Default

%description license
license components for the deprecated-pluggy package.


%package python
Summary: python components for the deprecated-pluggy package.
Group: Default

%description python
python components for the deprecated-pluggy package.


%prep
%setup -q -n pluggy-0.9.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554343668
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-pluggy
cp LICENSE %{buildroot}/usr/share/package-licenses/deprecated-pluggy/LICENSE
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-pluggy/LICENSE

%files python
%defattr(-,root,root,-)
